spring:
  cloud:
    gateway:
      routes:
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/departments/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

#     http://localhost:8000/users/2