server:
  port: 8000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

spring:

  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/departments/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

#     http://localhost:8000/users/2